title: IMGeo objectenhandboek
lang: nl
description: Praktijkhandleiding voor toepassing van de BGT|IMGeo standaarden bij de objectafbakening

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true
  
script: | 
  console.log("Hallo IMGeo objectenhandboek!");
  var url_prefix = "https://adbgnm.github.io/IMGeoOHtest/";
  var breadcrumbs = window.location.href.replace(url_prefix, '').split('/');
  breadcrumbs.forEach(addLink);
  function addLink(value, index, array) { array[index] = '<a href="/' + value + '">' + value + '</a>'; };
  document.getElementsByClassName("breadcrumb-item")[1].innerHTML = breadcrumbs.join(' / ').replace(/.html|.md/g, '');
  var toclevel1 = document.getElementsByClassName('level-1');
  for (let tocitem of toclevel1) { tocitem.getElementsByTagName('a')[0].innerHTML = tocitem.getElementsByTagName('a')[0].innerHTML.split('. ')[1];}
  document.getElementsByClassName('input-sm')[0].placeholder = "Zoeken in het objectenhandboek...";  
  if (document.getElementsByClassName('search-results').length > 0 ) { document.getElementsByClassName('search-results')[0].getElementsByTagName('h2')[0].innerHTML = 'Zoekresultaten';};
  if (document.getElementsByClassName('search-results').length > 0) {document.getElementsByClassName('search-results')[0].getElementsByClassName('summary')[0].innerHTML = document.getElementsByClassName('search-results')[0].getElementsByClassName('summary')[0].innerHTML.replace('Search finished, found', 'Zoekopdracht voltooid,').replace('page(s) matching the search query', 'pagina (\'s) gevonden die overeenkomen met de zoekopdracht');};
  var logo = document.createElement("div"); 
  var lgclass = document.createAttribute("id");      
  lgclass.value = "logo";                 
  logo.setAttributeNode(lgclass); 
  var content = document.getElementsByClassName("content")[0]; 
  content.insertBefore(logo, content.firstChild);   
  var lgimg = 'https://docs.geostandaarden.nl/bro/gen/logo_minbzk.png';
  document.getElementById("logo").innerHTML = '<img src="'+lgimg+'" title="Ministerie van BZK" />';
  document.getElementsByClassName('status')[0].getElementsByClassName('title')[0].innerHTML = '<i class="fa fa-book"></i> Beheer en licentie';
  document.getElementsByClassName('addons')[0].innerHTML = '<dl><dt><small>Geonovum ontwikkelt en beheert het digitale objectenhandboek BGT | IMGeo in opdracht van het Ministerie van Binnenlandse Zaken.<br /><br />Suggesties en (betere) foto\'s zijn van harte welkom op <a href="mailto:imgeo@geonovum.nl"> imgeo@geonovum.nl </a></small>.</dt></dl><hr />' + document.getElementsByClassName('addons')[0].innerHTML; 

scss: |
  @import url('https://tools.geostandaarden.nl/respec/style/fonts/ro-fonts.css');   
  .sidebar{background: #fff;}
  a {color:#008dc9;}
  .toctree a{color:#000; padding-left: 8}
  .toctree a:active {background: #fff;}
  .level-1, .level-2, .level-3, .level-4, .level-5 {background:#fff};
  body, .markdown-body {font-family: 'RO Sans', sans-serif;}  
  .markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4 {color: #00387d; font-family: 'RO Sans', sans-serif;}  
  .markdown-body blockquote {font-family: 'RO Serif', serif}
  .container{background: #fff;}
  .header{background: #008dc9;}
  .addons-wrap .status, addons {background:#007ea9;color:#000}
  .input-sm:before{content: " " }
  .header { display:none; }
  #logo img { width: 60%; margin-left: auto; margin-right: auto; display: block }
